# Nerual Networks and Deep Learning
http://neuralnetworksanddeeplearning.com/

##  Chapter 1

In [5]:
import numpy as np

In [85]:
# zip function

a = [1,2,3]
b = [10,20,30]
for i, j in (zip(a,b)):
    print(i,j)

print("\n")

sizes = [2,3,1]
print(sizes[1:])
print(sizes[:-1])

print("\n")

for x, y in (zip(sizes[:-1], sizes[1:])):
    print(np.random.randn(y, x))
    
print("\n")

zz = ([[1,2], [10,20], [100,200]])
yy = ([[1], [2], [3]])
for x, z in zip(zz,yy):
    print(x,z)

1 10
2 20
3 30


[3, 1]
[2, 3]


[[ 0.63120294  0.58595542]
 [ 0.51456038 -1.60393383]
 [ 0.80537377 -0.76728474]]
[[ 1.06862833 -0.43638407  0.23084483]]


[1, 2] [1]
[10, 20] [2]
[100, 200] [3]


### Initialize network
- The class takes in the size of the network. For example ```Network([2,3,1])``` has three layers with number of nodes in each layer. Layers are L0, L1, L2
- Class initalizes the size and number of layers
- **Biases**
    - It also assigns biases for each of the nodes starting from the L1 since L0 the input later. ```self.biases``` gives a list with ```length = number of layers - 1```. 
    - L0 = Input layer
    - L1 = Three nodes and three biases
    - L2 = One node and one bias
- **Weights**
    - From L0 to L1, two neurons go into three, so six weights are assigned. (3,2) matrix of weights
    - From L1 to L2, three neurons go into one, so three weights are assigned. (1,3) matrix of weights
- $\mathbf {wX + b}$


In [54]:
class Network(object):
    def __init__(self, sizes):
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]]
        self.weights = [np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]
        

net = Network([2,3,1])
print(net.sizes)
print(net.biases)
print(net.weights)


[2, 3, 1]
[array([[ 1.54715131],
       [-0.21973541],
       [-1.03595682]]), array([[0.57378319]])]
[array([[ 0.94154949, -0.43965656],
       [ 0.95935638, -0.08165227],
       [ 0.94874439, -0.33314255]]), array([[ 1.52501084, -0.93080075,  0.38855133]])]


array([[ 1.52501084, -0.93080075,  0.38855133]])

In [86]:
# define sigmoid function
def sigmoid(z):
    return 1.0/(1.0 + np.exp(z))

**Define the feedforward method, which gives the sigmoid output for a given input**
- This takes matrices w, A, and b and applies the sigma function to it.
- $\sigma(\mathbf {wA + b})$
- A is an (n,1) matrix

In [ ]:
def feedforward(self, a):
    for b, w in zip(self.biases, self, weights):
        a = sigmoid(np.dot(w,a) + b)
    

In [96]:
import mnist_loader

ModuleNotFoundError: No module named 'mnist_loader'